### ISSUE TITLE
Platform error sensor.google_fit - Integration 'google_fit' not found.

### ISSUE THREAD

**Issue by souravj96** [hemantkamalakar/google_fit_hass#3]
I'm using the latest version of google fit component

I have created google token by following [this link](https://www.home-assistant.io/integrations/calendar.google#prerequisites)
and my calendar is working fine. but when I adding the bellow code 
```
sensor:

  - platform: google_fit
    name: sourav
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret
    scan_interval: 300
```

I'm getting `Platform error sensor.google_fit - Integration 'google_fit' not found.` erron on Configuration validation
here is my folder structure.
![image](https://user-images.githubusercontent.com/52346695/82318503-9ab3e080-99ed-11ea-8a77-04e5e1d8cdc6.png)

did I miss anything?

**Comment by hemantkamalakar** [comment]
Please use following sensor definition 
```
sensor:
  - platform: google_fit_hass
    name: sourav
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret
    scan_interval: 300
```
